//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENCIAS_O365
    {
        public LICENCIAS_O365()
        {
            this.ESTADO_CUENTA_USUARIO = new HashSet<ESTADO_CUENTA_USUARIO>();
            this.MANTENEDOR_LICENCIA = new HashSet<MANTENEDOR_LICENCIA>();
        }
    
        public decimal IdLicencia { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<ESTADO_CUENTA_USUARIO> ESTADO_CUENTA_USUARIO { get; set; }
        public virtual ICollection<MANTENEDOR_LICENCIA> MANTENEDOR_LICENCIA { get; set; }
    }
}
