//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_INFO
    {
        public decimal IdInfo { get; set; }
        public string MsgInfo { get; set; }
        public string UserInfo { get; set; }
        public System.DateTime FechaInfo { get; set; }
        public int AccionIdInfo { get; set; }
    
        public virtual ACCION_INFO ACCION_INFO { get; set; }
    }
}
