//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENEDOR_LICENCIA
    {
        public decimal IdMantenedorLicencia { get; set; }
        public string Codigo { get; set; }
        public decimal RolCargoId { get; set; }
        public decimal LicenciaId { get; set; }
        public bool Vigente { get; set; }
    
        public virtual LICENCIAS_O365 LICENCIAS_O365 { get; set; }
        public virtual ROL_CARGO ROL_CARGO { get; set; }
    }
}
