//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmSysWebEntities : DbContext
    {
        public AdmSysWebEntities()
            : base("name=AdmSysWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCION_INFO> ACCION_INFO { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<ESTADO_ASIGNACION_LICENCIA> ESTADO_ASIGNACION_LICENCIA { get; set; }
        public virtual DbSet<ESTADO_CUENTA_USUARIO> ESTADO_CUENTA_USUARIO { get; set; }
        public virtual DbSet<ESTADO_REPORTE_LICENCIA> ESTADO_REPORTE_LICENCIA { get; set; }
        public virtual DbSet<ESTADO_SINCRONIZACION> ESTADO_SINCRONIZACION { get; set; }
        public virtual DbSet<LICENCIAS_O365> LICENCIAS_O365 { get; set; }
        public virtual DbSet<LOG_INFO> LOG_INFO { get; set; }
        public virtual DbSet<MANTENEDOR_LICENCIA> MANTENEDOR_LICENCIA { get; set; }
        public virtual DbSet<OFICINA> OFICINA { get; set; }
        public virtual DbSet<ORGANIZACION> ORGANIZACION { get; set; }
        public virtual DbSet<PAIS_REGION> PAIS_REGION { get; set; }
        public virtual DbSet<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
        public virtual DbSet<REPORTE_LICENCIA> REPORTE_LICENCIA { get; set; }
        public virtual DbSet<ROL_CARGO> ROL_CARGO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
