//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_USUARIO
    {
        public PERFIL_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IdPerfil { get; set; }
        public string NombrePerfil { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
