//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_LICENCIA
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string SamAccountName { get; set; }
        public string Description { get; set; }
        public string UpnPrefijo { get; set; }
        public string InfoString { get; set; }
        public string Licenses { get; set; }
        public string DistinguishedName { get; set; }
    }
}
