//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal Id { get; set; }
        public string Usuario1 { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public bool Visible { get; set; }
        public bool EsAdm { get; set; }
    
        public virtual PERFIL_USUARIO PERFIL_USUARIO { get; set; }
    }
}
